### ISSUE TITLE
AMAleg CAN transceiver details

### ISSUE THREAD

**Issue by arpad-boros** [Switchleg1/AMAleg#1]
Hi!
Some details are not clear for me related to the CAN transceiver, could you give me some help related to that?

1. Is 120 Ohm termination resistor needed on the CAN bus (so between CANH and CANL)?
2. In which mode do you use the SN65HVD23x chip? In high speed mode, or is it recommended to use slope control? If that is necessary, then what resistor value do you use on the Rs pin?

Thanks for your help!
Regards,
  Arpad

**Comment by Switchleg1** [comment]
You plan to build your own can transceiver board?  If so I would suggest
reading the datasheet, termination resistor isn't truly required but its
standard practice and comes included in the dev boards purchased from
amazon.  The dev boards should come with slope control enabled but
unfortunately I don't have any on hand to confirm.

**Comment by arpad-boros** [comment]
Hi!
Sorry for the late reaction, I forgot to write a response. :(
Yes I plan to build it on a prototype board, using an SO8 -> DIP8 converter, using the specific chip type.
On the picture you have uploaded [LINK](https://raw.githubusercontent.com/Switchleg1/AMAleg/main/diagram.jpg)
There are indeed two resistors:
- marked as 121 (120 Ohm, so a CAN bus termination resistor)
- marked as 103 (10 kOhm, probably for the slope control, which means slew rate of ~15 V/μs)
Then I guess you have not modified the board which came from Amazon, rather used it as is.

Thanks for your help!
Regards,
  Arpad

**Comment by Switchleg1** [comment]
Correct though I make my own boards now using the mcp2551 as it's more
readily available.
